version: '3.1'

services:
  factory-support-db:
    container_name: factory-support-db
    image: postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: 'factory-support'
      POSTGRES_PASSWORD: '1234'
      POSTGRES_USER: 'postgres'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@admin.com'
      PGADMIN_DEFAULT_PASSWORD: 'admin'
    restart: always
